from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

IMG_IQ = QImage("./img/iq-option.png")
IMG_UPLOAD = QImage("./img/upload.png")
IMG_LOGO = QImage("./img/logo.png")

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(820, 610)
		MainWindow.setMinimumSize(QSize(820, 610))
		MainWindow.setMaximumSize(QSize(820, 610))
		font = QFont()
		font.setFamily("Tahoma")
		MainWindow.setFont(font)
		icon = QIcon()
		icon.addPixmap(QPixmap(IMG_LOGO), QIcon.Selected, QIcon.On)
		MainWindow.setWindowIcon(icon)
		self.centralwidget = QWidget(MainWindow)
		self.centralwidget.setMinimumSize(QSize(820, 610))
		self.centralwidget.setMaximumSize(QSize(815, 610))
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout = QVBoxLayout(self.centralwidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.frame_2 = QFrame(self.centralwidget)
		self.frame_2.setMinimumSize(QSize(820, 610))
		self.frame_2.setFrameShape(QFrame.NoFrame)
		self.frame_2.setFrameShadow(QFrame.Raised)
		self.frame_2.setObjectName("frame_2")
		self.frame_3 = QFrame(self.frame_2)
		self.frame_3.setGeometry(QRect(-20, 0, 881, 641))
		self.frame_3.setMinimumSize(QSize(0, 0))
		self.frame_3.setStyleSheet("\n"
"background-color: rgb(58,58,58);")
		self.frame_3.setFrameShape(QFrame.NoFrame)
		self.frame_3.setFrameShadow(QFrame.Raised)
		self.frame_3.setObjectName("frame_3")
		self.topo = QFrame(self.frame_3)
		self.topo.setGeometry(QRect(0, 0, 850, 180))
		self.topo.setMinimumSize(QSize(0, 180))
		self.topo.setMaximumSize(QSize(16777215, 16777215))
		self.topo.setFrameShape(QFrame.NoFrame)
		self.topo.setFrameShadow(QFrame.Raised)
		self.topo.setObjectName("topo")
		self.horizontalLayout = QHBoxLayout(self.topo)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setSpacing(0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.login = QFrame(self.topo)
		self.login.setMinimumSize(QSize(0, 170))
		self.login.setMaximumSize(QSize(16777215, 16777215))
		self.login.setStyleSheet("\n"
"background-color: rgb(58,58,58);")
		self.login.setFrameShape(QFrame.NoFrame)
		self.login.setFrameShadow(QFrame.Raised)
		self.login.setLineWidth(0)
		self.login.setObjectName("login")
		self.lineEdit_email = QLineEdit(self.login)
		self.lineEdit_email.setGeometry(QRect(60, 70, 221, 31))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.lineEdit_email.setFont(font)
		self.lineEdit_email.setStyleSheet("QLineEdit{\n"
"border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		self.lineEdit_email.setText("")
		self.lineEdit_email.setMaxLength(32)
		self.lineEdit_email.setPlaceholderText("E-mail")
		self.lineEdit_email.setObjectName("lineEdit_email")
		self.lineEdit_senha = QLineEdit(self.login)
		self.lineEdit_senha.setGeometry(QRect(60, 110, 221, 31))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.lineEdit_senha.setFont(font)
		self.lineEdit_senha.setStyleSheet("QLineEdit{\n"
"border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		self.lineEdit_senha.setText("")
		self.lineEdit_senha.setMaxLength(20)
		self.lineEdit_senha.setEchoMode(QLineEdit.Password)
		self.lineEdit_senha.setObjectName("lineEdit_senha")
		self.label = QLabel(self.login)
		self.label.setGeometry(QRect(100, 10, 131, 51))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(13)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setStyleSheet("color: #f2f2f2")
		self.label.setScaledContents(True)
		self.label.setObjectName("label")
		self.pushButton_login = QPushButton(self.login)
		self.pushButton_login.setGeometry(QRect(310, 90, 71, 31))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.pushButton_login.setFont(font)
		self.pushButton_login.setStyleSheet("QPushButton{\n"
"border: 2px solid rgb(60,60,60);\n"
"color: #f2f2f2;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(254,101,0), stop:1 rgb(227, 90,0));\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(220,86,0)\n"
"}\n"
"")
		self.pushButton_login.setObjectName("pushButton_login")
		self.label_2 = QLabel(self.login)
		self.label_2.setGeometry(QRect(60, 20, 31, 31))
		self.label_2.setMaximumSize(QSize(16777215, 16777215))
		self.label_2.setText("")
		self.label_2.setPixmap(QPixmap(IMG_IQ))
		self.label_2.setScaledContents(True)
		self.label_2.setObjectName("label_2")
		self.line = QFrame(self.login)
		self.line.setGeometry(QRect(50, 150, 341, 16))
		self.line.setFrameShape(QFrame.HLine)
		self.line.setFrameShadow(QFrame.Sunken)
		self.line.setObjectName("line")
		self.line_3 = QFrame(self.login)
		self.line_3.setGeometry(QRect(170, 30, 221, 21))
		self.line_3.setFrameShape(QFrame.HLine)
		self.line_3.setFrameShadow(QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.line_4 = QFrame(self.login)
		self.line_4.setGeometry(QRect(40, 40, 16, 111))
		self.line_4.setFrameShape(QFrame.VLine)
		self.line_4.setFrameShadow(QFrame.Sunken)
		self.line_4.setObjectName("line_4")
		self.label_3 = QLabel(self.login)
		self.label_3.setGeometry(QRect(510, 10, 131, 51))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(13)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.label_3.setFont(font)
		self.label_3.setStyleSheet("color: #f2f2f2")
		self.label_3.setScaledContents(True)
		self.label_3.setObjectName("label_3")
		self.comboBox_listaCopy = QComboBox(self.frame_3)
		self.comboBox_listaCopy.setGeometry(QRect(465, 26, 195, 25))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(13)
		font.setItalic(False)
		font.setWeight(75)
		self.comboBox_listaCopy.setFont(font)
		self.comboBox_listaCopy.setStyleSheet("color: #f2f2f2; padding: 5px; background-color: rgb(58,58,58); border: none\n"
"\n"
"")
		self.comboBox_listaCopy.setObjectName("comboBox_listaCopy")
		self.label_4 = QLabel(self.login)
		self.label_4.setGeometry(QRect(470, 21, 27, 27))
		self.label_4.setText("")
		self.label_4.setScaledContents(True)
		self.label_4.setObjectName("label_4")
		self.line_5 = QFrame(self.login)
		self.line_5.setGeometry(QRect(450, 40, 16, 111))
		self.line_5.setFrameShape(QFrame.VLine)
		self.line_5.setFrameShadow(QFrame.Sunken)
		self.line_5.setObjectName("line_5")
		self.line_6 = QFrame(self.login)
		self.line_6.setGeometry(QRect(460, 150, 341, 16))
		self.line_6.setFrameShape(QFrame.HLine)
		self.line_6.setFrameShadow(QFrame.Sunken)
		self.line_6.setObjectName("line_6")
		self.line_8 = QFrame(self.login)
		self.line_8.setGeometry(QRect(800, 40, 20, 111))
		self.line_8.setFrameShape(QFrame.VLine)
		self.line_8.setFrameShadow(QFrame.Sunken)
		self.line_8.setObjectName("line_8")
		self.label_5 = QLabel(self.login)
		self.label_5.setGeometry(QRect(575, 90, 21, 21))
		self.label_5.setText("")
		self.label_5.setPixmap(QPixmap(IMG_UPLOAD))
		self.label_5.setScaledContents(True)
		self.label_5.setObjectName("label_5")
		self.radioButton_Copy = QRadioButton(self.login)
		self.radioButton_Copy.setGeometry(QRect(520, 129, 21, 20))
		self.radioButton_Copy.setObjectName("radioButton_Copy")
		self.radioButton_Posicao = QRadioButton(self.login)
		self.radioButton_Posicao.setGeometry(QRect(550, 102, 21, 20))
		self.radioButton_Posicao.setObjectName("radioButton_Posicao")
		self.label_8 = QLabel(self.login)
		self.label_8.setGeometry(QRect(620, 70, 120, 65))
		font = QFont()
		font.setPointSize(11)
		font.setFamily("Tahoma")
		font.setLetterSpacing(QFont.AbsoluteSpacing, 1.2)
		self.label_8.setFont(font)
		self.label_8.setStyleSheet("color: #f2f2f2;")
		self.label_8.setObjectName("label_8")
		self.line_21 = QFrame(self.login)
		self.line_21.setGeometry(QRect(390, 40, 20, 111))
		self.line_21.setFrameShape(QFrame.VLine)
		self.line_21.setFrameShadow(QFrame.Sunken)
		self.line_21.setObjectName("line_21")
		self.pushButton_chooseFile = QPushButton(self.login)
		self.pushButton_chooseFile.setGeometry(QRect(530, 92, 21, 20))
		self.pushButton_chooseFile.setStyleSheet("background-color: #f2f2f2;\n border-radius: 3px"
"")
		self.pushButton_chooseFile.setObjectName("pushButton_chooseFile")
		self.lineEdit_email.raise_()
		self.lineEdit_senha.raise_()
		self.label.raise_()
		self.pushButton_login.raise_()
		self.label_2.raise_()
		self.line.raise_()
		self.line_4.raise_()
		self.label_3.raise_()
		self.label_4.raise_()
		self.line_5.raise_()
		self.line_6.raise_()
		self.line_8.raise_()
		self.label_5.raise_()
		self.label_8.raise_()
		self.line_3.raise_()
		self.line_21.raise_()
		self.pushButton_chooseFile.raise_()
		self.horizontalLayout.addWidget(self.login)
		self.line_7 = QFrame(self.frame_3)
		self.line_7.setGeometry(QRect(590, 25, 211, 31))
		self.line_7.setFrameShape(QFrame.HLine)
		self.line_7.setFrameShadow(QFrame.Sunken)
		self.line_7.setObjectName("line_7")
		self.label_9 = QLabel(self.frame_3)
		self.label_9.setGeometry(QRect(85, 165, 81, 31))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(13)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.label_9.setFont(font)
		self.label_9.setStyleSheet("color: #f2f2f2")
		self.label_9.setScaledContents(True)
		self.label_9.setObjectName("label_9")
		self.line_9 = QFrame(self.frame_3)
		self.line_9.setGeometry(QRect(170, 170, 611, 31))
		self.line_9.setFrameShape(QFrame.HLine)
		self.line_9.setFrameShadow(QFrame.Sunken)
		self.line_9.setObjectName("line_9")
		self.line_10 = QFrame(self.frame_3)
		self.line_10.setGeometry(QRect(70, 190, 16, 41))
		self.line_10.setFrameShape(QFrame.VLine)
		self.line_10.setFrameShadow(QFrame.Sunken)
		self.line_10.setObjectName("line_10")
		self.line_11 = QFrame(self.frame_3)
		self.line_11.setGeometry(QRect(80, 220, 701, 31))
		self.line_11.setFrameShape(QFrame.HLine)
		self.line_11.setFrameShadow(QFrame.Sunken)
		self.line_11.setObjectName("line_11")
		self.line_12 = QFrame(self.frame_3)
		self.line_12.setGeometry(QRect(770, 190, 21, 41))
		self.line_12.setFrameShape(QFrame.VLine)
		self.line_12.setFrameShadow(QFrame.Sunken)
		self.line_12.setObjectName("line_12")
		self.comboBox_chooseMode = QComboBox(self.frame_3)
		self.comboBox_chooseMode.setGeometry(QRect(630, 198, 120, 25))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(11)
		self.comboBox_chooseMode.setFont(font)
		self.comboBox_chooseMode.setStyleSheet("color: #f2f2f2; padding: 5px; background-color: rgb(58,58,58); border: none\n"
"\n"
"")
		self.comboBox_chooseMode.setObjectName("comboBox_chooseMode")
		self.comboBox_chooseCountry = QComboBox(self.login)
		self.comboBox_chooseCountry.setGeometry(QRect(500, 65, 114, 26))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.comboBox_chooseCountry.setPlaceholderText('Região')
		font.setLetterSpacing(QFont.AbsoluteSpacing, 1.1)
		self.comboBox_chooseCountry.setFont(font)
		self.comboBox_chooseCountry.setStyleSheet("QComboBox {padding: 5px; background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190); border-radius: 4px; border: none}")
		self.comboBox_chooseCountry.setObjectName("comboBox_chooseCountry")
		self.label_10 = QLabel(self.frame_3)
		self.label_10.setGeometry(QRect(280, 191, 61, 41))
		font = QFont()
		font.setPointSize(11)
		font.setFamily("Tahoma")
		self.label_10.setFont(font)
		self.label_10.setStyleSheet("color: #f2f2f2;")
		self.label_10.setObjectName("label_10")
		self.line_13 = QFrame(self.frame_3)
		self.line_13.setGeometry(QRect(40, 260, 16, 81))
		self.line_13.setFrameShape(QFrame.VLine)
		self.line_13.setFrameShadow(QFrame.Sunken)
		self.line_13.setObjectName("line_13")
		self.line_14 = QFrame(self.frame_3)
		self.line_14.setGeometry(QRect(50, 340, 751, 20))
		self.line_14.setFrameShape(QFrame.HLine)
		self.line_14.setFrameShadow(QFrame.Sunken)
		self.line_14.setObjectName("line_14")
		self.line_15 = QFrame(self.frame_3)
		self.line_15.setGeometry(QRect(800, 260, 16, 81))
		self.line_15.setFrameShape(QFrame.VLine)
		self.line_15.setFrameShadow(QFrame.Sunken)
		self.line_15.setObjectName("line_15")
		self.line_16 = QFrame(self.frame_3)
		self.line_16.setGeometry(QRect(220, 250, 581, 20))
		self.line_16.setFrameShape(QFrame.HLine)
		self.line_16.setFrameShadow(QFrame.Sunken)
		self.line_16.setObjectName("line_16")
		self.label_12 = QLabel(self.frame_3)
		self.label_12.setGeometry(QRect(100, 280, 71, 19))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.label_12.setFont(font)
		self.label_12.setStyleSheet("color: #f2f2f2")
		self.label_12.setObjectName("label_12")
		self.spinBox_valueEntry = QDoubleSpinBox(self.frame_3)
		self.spinBox_valueEntry.setGeometry(QRect(84, 300, 61, 31))
		self.spinBox_valueEntry.setStyleSheet("QDoubleSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QDoubleSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_valueEntry.setDecimals(1)
		self.spinBox_valueEntry.setFont(font)
		self.spinBox_valueEntry.setButtonSymbols(QAbstractSpinBox.NoButtons)
		self.spinBox_valueEntry.setRange(1,10000000)
		self.spinBox_valueEntry.setObjectName("spinBox_valueEntry")
		self.label_13 = QLabel(self.frame_3)
		self.label_13.setGeometry(QRect(110, 190, 141, 41))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(11)
		self.label_13.setAlignment(Qt.AlignCenter)
		self.label_13.setFont(font)
		self.label_13.setStyleSheet("color: #FF6347;")
		self.label_13.setObjectName("label_13")
		self.label_14 = QLabel(self.frame_3)
		self.label_14.setGeometry(QRect(220, 280, 61, 21))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.label_14.setFont(font)
		self.label_14.setStyleSheet("color: #f2f2f2")
		self.label_14.setObjectName("label_14")
		self.spinBox_stopWin = QDoubleSpinBox(self.frame_3)
		self.spinBox_stopWin.setGeometry(QRect(207, 300, 61, 31))
		self.spinBox_stopWin.setStyleSheet("QDoubleSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QDoubleSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_stopWin.setFont(font)
		self.spinBox_stopWin.setDecimals(1)
		self.spinBox_stopWin.setRange(1,1000000)
		self.spinBox_stopWin.setButtonSymbols(QAbstractSpinBox.NoButtons)
		self.spinBox_stopWin.setObjectName("spinBox_stopWin")
		self.spinBox_stopLoss = QDoubleSpinBox(self.frame_3)
		self.spinBox_stopLoss.setGeometry(QRect(330, 300, 61, 31))
		self.spinBox_stopLoss.setStyleSheet("QDoubleSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QDoubleSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_stopLoss.setFont(font)
		self.spinBox_stopLoss.setDecimals(1)
		self.spinBox_stopLoss.setButtonSymbols(QAbstractSpinBox.NoButtons)
		self.spinBox_stopLoss.setRange(1,1000000)
		self.spinBox_stopLoss.setObjectName("spinBox_stopLoss")
		self.label_16 = QLabel(self.frame_3)
		self.label_16.setGeometry(QRect(342, 280, 61, 21))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.label_16.setFont(font)
		self.label_16.setStyleSheet("color: #f2f2f2")
		self.label_16.setObjectName("label_16")
		self.label_18 = QLabel(self.frame_3)
		self.label_18.setGeometry(QRect(80, 280, 16, 19))
		font = QFont()
		font.setPointSize(10)
		self.label_18.setFont(font)
		self.label_18.setStyleSheet("color: rgb(245, 119, 41)")
		self.label_18.setObjectName("label_18")
		self.label_19 = QLabel(self.frame_3)
		self.label_19.setGeometry(QRect(200, 280, 16, 19))
		font = QFont()
		font.setPointSize(10)
		self.label_19.setFont(font)
		self.label_19.setStyleSheet("color: rgb(245, 119, 41)")
		self.label_19.setObjectName("label_19")
		self.label_20 = QLabel(self.frame_3)
		self.label_20.setGeometry(QRect(322, 280, 81, 20))
		font = QFont()
		font.setPointSize(10)
		self.label_20.setFont(font)
		self.label_20.setStyleSheet("color: rgb(245, 119, 41)")
		self.label_20.setObjectName("label_20")
		self.pushButton_start = QPushButton(self.frame_3)
		self.pushButton_start.setGeometry(QRect(600, 294, 91, 41))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		font.setLetterSpacing(QFont.AbsoluteSpacing, 1.2)
		self.pushButton_start.setFont(font)
		self.pushButton_start.setStyleSheet("QPushButton{\n"
"border: 2px solid rgb(60,60,60);\n"
"color: #f2f2f2;\n"
"background-color: rgb(7, 173, 68);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(6, 157, 62)\n"
"}\n"
"")
		self.pushButton_start.setObjectName("pushButton_start")
		self.pushButton_stop = QPushButton(self.frame_3)
		self.pushButton_stop.setGeometry(QRect(700, 294, 91, 41))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		font.setLetterSpacing(QFont.AbsoluteSpacing, 1.2)
		self.pushButton_stop.setFont(font)
		self.pushButton_stop.setStyleSheet("QPushButton{\n"
"border: 2px solid rgb(60,60,60);\n"
"color: #f2f2f2;\n"
"background-color: rgb(205, 0, 20);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(188, 0, 18);\n"
"}\n"
"")
		self.pushButton_stop.setObjectName("pushButton_stop")
		self.label_21 = QLabel(self.frame_3)
		self.label_21.setGeometry(QRect(60, 360, 191, 31))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(13)
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		self.label_21.setFont(font)
		self.label_21.setStyleSheet("color: #f2f2f2")
		self.label_21.setScaledContents(True)
		self.label_21.setObjectName("label_21")
		self.line_17 = QFrame(self.frame_3)
		self.line_17.setGeometry(QRect(220, 370, 581, 20))
		self.line_17.setFrameShape(QFrame.HLine)
		self.line_17.setFrameShadow(QFrame.Sunken)
		self.line_17.setObjectName("line_17")
		self.line_18 = QFrame(self.frame_3)
		self.line_18.setGeometry(QRect(800, 380, 20, 191))
		self.line_18.setFrameShape(QFrame.VLine)
		self.line_18.setFrameShadow(QFrame.Sunken)
		self.line_18.setObjectName("line_18")
		self.line_19 = QFrame(self.frame_3)
		self.line_19.setGeometry(QRect(40, 380, 20, 191))
		self.line_19.setFrameShape(QFrame.VLine)
		self.line_19.setFrameShadow(QFrame.Sunken)
		self.line_19.setObjectName("line_19")
		self.line_20 = QFrame(self.frame_3)
		self.line_20.setGeometry(QRect(50, 570, 751, 20))
		self.line_20.setFrameShape(QFrame.HLine)
		self.line_20.setFrameShadow(QFrame.Sunken)
		self.line_20.setObjectName("line_20")
		self.spinBox_ranking = QSpinBox(self.login)
		self.spinBox_ranking.setRange(1,100)
		self.spinBox_ranking.setSuffix("°")
		self.spinBox_ranking.setButtonSymbols(QAbstractSpinBox.NoButtons)
		self.spinBox_ranking.setGeometry(QRect(625, 126, 41, 25))
		self.spinBox_ranking.setStyleSheet("QSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_ranking.setFont(font)
		self.spinBox_ranking.setObjectName("spinBox_ranking")
		self.spinBox_rankingFixo = QSpinBox(self.login)
		self.spinBox_rankingFixo.setSuffix("°")
		self.spinBox_rankingFixo.setButtonSymbols(QAbstractSpinBox.NoButtons)
		self.spinBox_rankingFixo.setRange(1, 10000)
		self.spinBox_rankingFixo.setGeometry(QRect(647, 98, 41, 25))
		self.spinBox_rankingFixo.setStyleSheet("QSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_rankingFixo.setFont(font)
		self.spinBox_rankingFixo.setObjectName("spinBox_rankingFixo")
		self.spinBox_ranking1 = QSpinBox(self.login)
		self.spinBox_ranking1.setSuffix("°")
		self.spinBox_ranking1.setButtonSymbols(QAbstractSpinBox.NoButtons)
		self.spinBox_ranking1.setRange(1, 10000)
		self.spinBox_ranking1.setGeometry(QRect(681, 126, 41, 25))
		self.spinBox_ranking1.setStyleSheet("QSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_ranking1.setFont(font)
		self.spinBox_ranking1.setObjectName("spinBox_ranking1")
		self.spinBox_valorMin = QSpinBox(self.login)
		self.spinBox_valorMin.setPrefix("$ ")
		self.spinBox_valorMin.setButtonSymbols(QAbstractSpinBox.NoButtons)
		self.spinBox_valorMin.setRange(1, 100000000)
		self.spinBox_valorMin.setGeometry(QRect(675, 70, 60, 25))
		self.spinBox_valorMin.setStyleSheet("QSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_valorMin.setFont(font)
		self.spinBox_valorMin.setObjectName("spinBox_valorMin")
		self.check_porcentagem = QCheckBox(self.frame_3)
		self.check_porcentagem.setGeometry(QRect(554, 303, 25, 10))
		self.check_porcentagem.setObjectName("check_porcentagem")
		self.spinBox_martingale = QSpinBox(self.frame_3)
		self.spinBox_martingale.setGeometry(QRect(453, 300, 61, 31))
		self.spinBox_martingale.setStyleSheet("QSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_martingale.setFont(font)
		self.spinBox_martingale.setObjectName("spinBox_martingale")
		self.label_23 = QLabel(self.frame_3)
		self.label_23.setGeometry(QRect(462, 282, 81, 16))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.label_23.setFont(font)
		self.label_23.setStyleSheet("color: #f2f2f2")
		self.label_23.setObjectName("label_23")
		self.label_29 = QLabel(self.login)
		self.label_29.setGeometry(QRect(670, 131, 10, 16))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.label_29.setFont(font)
		self.label_29.setStyleSheet("color: #f2f2f2")
		self.label_29.setObjectName("label_29")
		self.label_30 = QLabel(self.login)
		self.label_30.setGeometry(QRect(578, 104, 70, 16))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		font.setLetterSpacing(QFont.AbsoluteSpacing, 1.2)
		self.label_30.setFont(font)
		self.label_30.setStyleSheet("color: #f2f2f2")
		self.label_30.setObjectName("label_30")
		self.label_31 = QLabel(self.frame_3)
		self.label_31.setGeometry(QRect(543, 306, 53, 31))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		font.setLetterSpacing(QFont.AbsoluteSpacing, 1.2)
		self.label_31.setFont(font)
		self.label_31.setStyleSheet("color: #f2f2f2")
		self.label_31.setObjectName("label_31")
		self.label_32 = QLabel(self.frame_3)
		self.label_32.setGeometry(QRect(48, 242, 170, 27))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.label_32.setFont(font)
		self.label_32.setStyleSheet("color: #f2f2f2; padding: 5px; background-color: rgb(58,58,58); border: none\n"
"\n"
"")
		self.label_32.setObjectName("label_32")
		self.label_24 = QLabel(self.frame_3)
		self.label_24.setGeometry(QRect(442, 280, 81, 20))
		font = QFont()
		font.setPointSize(10)
		self.label_24.setFont(font)
		self.label_24.setStyleSheet("color: rgb(245, 119, 41)")
		self.label_24.setObjectName("label_24")
		self.label_26 = QLabel(self.login)
		font.setPointSize(10)
		font.setFamily("Tahoma")
		font.setLetterSpacing(QFont.AbsoluteSpacing, 1.2)
		self.label_26.setFont(font)
		self.label_26.setGeometry(QRect(544, 130, 80, 16))
		self.label_26.setStyleSheet("color: #f2f2f2")
		self.label_26.setObjectName("label_26")
		self.label_27 = QLabel(self.frame_3)
		self.label_27.setGeometry(QRect(438, 190, 141, 11))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(8)
		self.label_27.setFont(font)
		self.label_27.setStyleSheet("color: #F2F2F2;")
		self.label_27.setObjectName("label_27")
		self.label_28 = QLabel(self.login)
		self.label_28.setGeometry(QRect(640, 52, 130, 18))
		self.label_28.setAlignment(Qt.AlignCenter)
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(8)
		self.label_28.setFont(font)
		self.label_28.setStyleSheet("color: #F2F2F2;")
		self.label_28.setObjectName("label_28")
		self.spinBox_ranking.hide()
		self.spinBox_ranking1.hide()
		self.label_26.hide()
		self.label_28.hide()
		self.label_29.hide()
		self.label_30.hide()
		self.radioButton_Copy.hide()
		self.spinBox_rankingFixo.hide()
		self.radioButton_Posicao.hide()
		self.comboBox_chooseCountry.hide()
		self.spinBox_valorMin.hide()
		self.spinBox_gerenciamento = QDoubleSpinBox(self.frame_3)
		self.spinBox_gerenciamento.setGeometry(QRect(438, 204, 121, 25))
		self.spinBox_gerenciamento.setStyleSheet("QDoubleSpinBox {border: 3px rgb(45,45,45);\n"
"border-radius: 4px;\n"
"padding: 6px;\n"
"background-color: rgb(30,30,30);\n"
"color: rgb(190,190, 190);\n"
"}\n"
"QDoubleSpinBox:focus {\n"
"border: 2px solid rgb(254, 101, 0)\n"
"}")
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(10)
		self.spinBox_gerenciamento.setAlignment(Qt.AlignCenter)
		self.spinBox_gerenciamento.setFont(font)
		self.spinBox_gerenciamento.setObjectName("spinBox_gerenciamento")
		self.spinBox_gerenciamento.setButtonSymbols(QAbstractSpinBox.NoButtons) 
		self.spinBox_gerenciamento.setRange(1.0,10000000000.000)
		self.spinBox_gerenciamento.setPrefix("$ ")
		self.label_5.hide()
		self.label_8.hide()
		self.pushButton_chooseFile.hide()
		self.label_footer = QLabel(self.frame_3)
		self.label_footer.setGeometry(QRect(282, 580, 310, 31))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(8)
		font.setWeight(75)
		self.label_footer.setFont(font)
		self.label_footer.setStyleSheet("color: #888")
		self.label_footer.setObjectName("label_footer")
		self.label_footer.setOpenExternalLinks(True)
		self.textEdit_output = QTextEdit(self.frame_3)
		self.textEdit_output.setGeometry(QRect(70, 400, 355, 161)) 
		self.textEdit_output.setObjectName("textEdit_output")
		self.textEdit_output.setStyleSheet("color: rgb(255,255,255);border: 1px solid #2a2a2a;")
		self.textEdit_output.setReadOnly(True)
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(11)
		self.textEdit_output.setFont(font)
		self.textEdit_terminal = QTextEdit(self.frame_3)
		self.textEdit_terminal.setGeometry(QRect(435, 400, 355, 161)) 
		self.textEdit_terminal.setObjectName("textEdit_terminal")
		self.textEdit_terminal.setStyleSheet("color: rgb(255,255,255); border: 1px solid #2a2a2a")
		self.textEdit_terminal.setReadOnly(True)
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(11)
		self.textEdit_terminal.setFont(font)
		self.label_banca = QLabel(self.frame_3)
		self.label_banca.setGeometry(QRect(295, 191, 100, 41))
		font = QFont()
		font.setFamily("Tahoma")
		font.setPointSize(11)
		self.label_banca.setFont(font)
		self.label_banca.setStyleSheet("color: rgb(255,255,255)")
		self.label_banca.setObjectName("label_banca")
		self.label_24.raise_()
		self.topo.raise_()
		self.line_7.raise_()
		self.line_9.raise_()
		self.line_10.raise_()
		self.line_11.raise_()
		self.line_12.raise_()
		self.comboBox_chooseMode.raise_()
		self.comboBox_chooseCountry.raise_()
		self.spinBox_ranking.raise_()
		self.spinBox_ranking1.raise_()
		self.spinBox_rankingFixo.raise_()
		self.spinBox_valorMin.raise_()
		self.label_10.raise_()
		self.line_13.raise_()
		self.line_14.raise_()
		self.line_15.raise_()
		self.line_16.raise_()
		self.label_12.raise_()
		self.spinBox_valueEntry.raise_()
		self.label_13.raise_()
		self.label_14.raise_()
		self.spinBox_stopWin.raise_()
		self.label_18.raise_()
		self.label_19.raise_()
		self.label_20.raise_()
		self.label_16.raise_()
		self.spinBox_stopLoss.raise_()
		self.label_9.raise_()
		self.pushButton_start.raise_()
		self.pushButton_stop.raise_()
		self.label_21.raise_()
		self.line_17.raise_()
		self.line_18.raise_()
		self.line_19.raise_()
		self.line_20.raise_()
		self.spinBox_martingale.raise_()
		self.label_23.raise_()
		self.label_26.raise_()
		self.label_27.raise_()
		self.label_28.raise_()
		self.label_29.raise_()
		self.label_31.raise_()
		self.label_footer.raise_()
		self.label_32.raise_()
		self.textEdit_output.raise_()
		self.textEdit_terminal.raise_()
		self.label_banca.raise_()
		self.radioButton_Copy.raise_()
		self.radioButton_Posicao.raise_()
		self.spinBox_gerenciamento.raise_()
		self.comboBox_listaCopy.raise_()
		self.check_porcentagem.raise_()
		self.verticalLayout.addWidget(self.frame_2)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "LogroBot - IQ Automática"))
		self.lineEdit_senha.setPlaceholderText(_translate("MainWindow", "Senha"))
		self.label.setText(_translate("MainWindow", "LOGIN"))
		self.pushButton_login.setText(_translate("MainWindow", "Entrar"))
		self.label_3.setText(_translate("MainWindow", "GERAL"))
		self.label_8.setText(_translate("MainWindow", "Carregar lista"))
		self.pushButton_chooseFile.setText(_translate("MainWindow", "..."))
		self.radioButton_Copy.setText(_translate("MainWindow", ""))
		self.radioButton_Posicao.setText(_translate("MainWindow", ""))
		self.label_9.setText(_translate("MainWindow", "STATUS"))
		self.comboBox_chooseMode.setItemText(0, _translate("MainWindow", "Treinamento"))
		self.comboBox_chooseMode.setItemText(1, _translate("MainWindow", "Conta Real"))
		self.comboBox_chooseCountry.setItemText(0, _translate("MainWindow", "Worldwide"))
		self.comboBox_chooseCountry.setItemText(1, _translate("MainWindow", "BR"))
		self.comboBox_listaCopy.setItemText(0, _translate("MainWindow", ""))
		self.comboBox_listaCopy.setItemText(1, _translate("MainWindow", ""))
		self.label_10.setText(_translate("MainWindow", '<span style="color: rgb(245, 119, 41);">$</span>'))
		self.label_12.setText(_translate("MainWindow", "Entrada"))
		self.label_13.setText(_translate("MainWindow", "Desconectado"))
		self.label_14.setText(_translate("MainWindow", "Stop Win"))
		self.label_16.setText(_translate("MainWindow", "Stop Loss"))
		self.label_18.setText(_translate("MainWindow", " $"))
		self.label_19.setText(_translate("MainWindow", "✓"))
		self.label_20.setText(_translate("MainWindow", "✕"))
		self.pushButton_start.setText(_translate("MainWindow", "COMEÇAR"))
		self.pushButton_stop.setText(_translate("MainWindow", "PARAR"))
		self.label_21.setText(_translate("MainWindow", "LISTA DE SINAIS"))
		self.label_23.setText(_translate("MainWindow", "Martingale"))
		self.label_32.setText(_translate("MainWindow", "CONFIGURAÇÕES"))
		self.label_24.setText(_translate("MainWindow", "⟲"))
		self.label_banca.setText(_translate("MainWindow", ""))
		self.label_26.setText(_translate("MainWindow", "Sequência"))
		self.label_footer.setText(_translate("MainWindow", "LogroBot V1.0.0 Estável - <a href=\"https://irangarcia.dev/logrobot/index.html\"><span style=\"color:rgb(245, 119, 41);\">irangarcia.dev/logrobot"))
		self.label_27.setText(_translate("MainWindow", "Gerenciamento de Banca"))
		self.label_28.setText(_translate("MainWindow", "Entrada Mínima Trader"))
		self.label_29.setText(_translate("MainWindow", "-"))
		self.label_30.setText(_translate("MainWindow", "Posição"))
		self.label_31.setText(_translate("MainWindow", "Em %"))

if __name__ == "__main__":
	import sys
	app = QApplication(sys.argv)
	MainWindow = QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
